"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-08-13 17:42:43.164305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('dest_path', sa.String(length=500), nullable=False),
    sa.Column('transfer_mode', sa.String(length=8), nullable=False),
    sa.Column('duplicate_strategy', sa.String(length=12), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=64), nullable=True),
    sa.Column('immich_status', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('orientation', sa.String(length=12), nullable=True),
    sa.Column('filename_regex', sa.String(length=300), nullable=True),
    sa.Column('camera_make', sa.String(length=120), nullable=True),
    sa.Column('camera_model', sa.String(length=120), nullable=True),
    sa.Column('dest_template', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=True),
    sa.Column('orientation', sa.String(length=12), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(length=120), nullable=True),
    sa.Column('camera_model', sa.String(length=120), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('planned_dest', sa.String(length=1024), nullable=True),
    sa.Column('final_dest', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_items_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_items_job_id'))

    op.drop_table('job_items')
    op.drop_table('settings')
    op.drop_table('rules')
    op.drop_table('jobs')
    # ### end Alembic commands ###
